name: Aliyun Signin

on:
  schedule:
   # 每天国际时间 17:20 运行一次, 中国时间 01:20
    - cron: '10 18 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
    env:
      random: ${{RANDOM%60}}
      
    steps:
      - name: delay
        run: |
          echo "random:${{env.random}}"
          sleep env.random
        
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: ${{ secrets.ALITOKEN }}
          GP_TOKEN: ${{ secrets.TOKEN}}
