name: Spider Jar Gen CI

on: workflow_dispatch

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - id: clone-project-FongMi
      name: Clone FongMi project
      run: git clone --depth=1 'https://github.com/FongMi/CatVodSpider' project
      
    - id: clone-project-My
      name: Clone My project
      run: git clone --depth=1 'https://github.com/Wirili/CatVodSpider_my' project-my
      
    - id: move-files
      name: move files
      run:  move ./project-my  ./project
      
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        
    - name: Build with Gradle
      run: ./project/build.bat ec

    - name: move files 2
      run:  replace ./project/jar/custom_spider.jar ./custom_spider.jar
      
    - name: move files 3
      run:  replace ./project/jar/custom_spider.jar.md5 ./custom_spider.jar.md5
      
    - name: Update spider jar
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'update spider jar'
        add: "['./custom_spider.jar', './custom_spider.jar.md5']"
