name: ZAliyun Signin

on:
  #schedule:
   # 每天国际时间 23:10 运行一次, 中国时间 7:10
   # - cron: '10 23 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
      
    steps:
      - uses: Wirili/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: ${{ secrets.ALITOKEN }}
          GP_TOKEN: ${{ secrets.TOKEN}}
