name: ZAliyun Signin

on:
  schedule:
   # 每天国际时间 17:20 运行一次, 中国时间 01:20
    - cron: '10 18 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
      
    steps:
      - name: Get Random
        run: |
          rad = "$(echo "RANDOM%10")"
          echo $rad
          sleep $rad
          
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: ${{ secrets.ALITOKEN }}
          GP_TOKEN: ${{ secrets.TOKEN}}
